# Generated by Django 3.0.1 on 2020-01-03 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city_destination', '0001_initial'),
        ('city', '0001_initial'),
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_time', models.DateTimeField(blank=True)),
                ('airways', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='airlines.Airlines')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='city_destination.CityDestination')),
                ('from_where', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='city.City')),
            ],
        ),
    ]
