# Generated by Django 3.0.1 on 2020-01-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flights_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
