# Generated by Django 3.0.1 on 2020-01-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20200103_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
