# Generated by Django 3.0.1 on 2020-01-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20200103_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
