# Generated by Django 3.0.1 on 2020-01-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airways_name', models.CharField(max_length=200)),
                ('airways_flight_code', models.CharField(max_length=200)),
                ('airways_logo', models.ImageField(upload_to='photos/%airways/')),
            ],
        ),
    ]
