# Generated by Django 3.0.1 on 2020-01-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlines',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
